### ISSUE TITLE
unable to access the service

### ISSUE THREAD

**Issue by razavistag** [fr0gger/Awesome-GPT-Agents#19]
![image](https://github.com/fr0gger/Awesome-GPT-Agents/assets/79866399/acbf9613-425e-44eb-8284-35248f684bdd)

receiving this message and it is redirecting into chatgpt 3.5. please explain how we can access those models

**Comment by boredgamesdev** [comment]
They are only available to ChatGPT Plus and Enterprise users at this time.

**Comment by fr0gger** [comment]
Yes we put that information in the page :)
